name: CI - API

on:
  push:
    paths:
      - 'fastapi/**'
      - '.github/workflows/ci-api.yml'

  pull_request:
    paths:
      - 'fastapi/**'
      - '.github/workflows/ci-api.yml'

jobs:
  test-api:
    runs-on: ubuntu-latest
    env:
      PYTHONUTF8: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: api-${{ hashFiles('fastapi/requirements.txt', 'fastapi/requirements-dev.txt') }}
          restore-keys: |
            api-

      - name: Install dependencies (fastapi)
        working-directory: fastapi
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -r requirements.txt
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; else pip install pytest; fi

      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/fastapi" >> $GITHUB_ENV

      - name: Sanity import
        working-directory: fastapi
        run: python -c "import app, sys; print('app OK ->', app.__file__)"

      - name: Run tests
        working-directory: fastapi
        run: pytest -q
