name: CI • Windows Self-Hosted + GPU

on: [push, pull_request]

jobs:
  gpu-tests:
    runs-on: [self-hosted, windows, gpu, cuda, nvidia]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements-gpu.txt
      - run: pytest -m "gpu" -q
