name: Windows CI

on:
  push:
    paths:
      - 'fastapi/**'
      - '.github/workflows/ci-windows.yml'
  pull_request:
    paths:
      - 'fastapi/**'
      - '.github/workflows/ci-windows.yml'



jobs:
  test:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: windows-${{ runner.os }}-${{ hashFiles('fastapi/requirements.txt', 'fastapi/requirements-dev.txt') }}

      - name: Install dependencies (fastapi)
        working-directory: fastapi
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          if (Test-Path requirements-dev.txt) { python -m pip install -r requirements-dev.txt } else { python -m pip install pytest }

      - name: Sanity import
        working-directory: fastapi
        run: python -c "import app; print('app OK')"

      - name: Run tests
        working-directory: fastapi
        run: python -m pytest -q
